name: Deploy ADF DEV → STAGE

on:
  push:
    branches:
      - adf_publish   # Se dispara cuando haces Publish en ADF

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a Azure con usuario/password (sandbox)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "dummy",
              "clientSecret": "dummy",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "username": "${{ secrets.AZURE_USERNAME }}",
              "password": "${{ secrets.AZURE_PASSWORD }}"
            }

      # 3. Deploy del ARM template al ADF Stage
      - name: Deploy ADF to STAGE
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: 1-79a159cd-playground-sandbox
          template: ./adf_publish/ARMTemplateForFactory.json
          parameters: ./adf_publish/ARMTemplateParametersForFactory.json
          overrideParameters: >
            -factoryName adfpocstage918732
